kind: pipeline
type: docker
name: deploy

clone:
  disable: true

steps:
  - name: clone-code
    image: alpine/git
    commands:
      - git clone http://172.17.0.1:3001/Bayo/Porfolio-website.git .
      - git checkout ${DRONE_COMMIT}

  - name: build-and-push
    image: plugins/docker
    settings:
      registry: 10.0.0.2
      repo: 10.0.0.2/library/portfolio
      tags:
        - latest
        - build-${DRONE_BUILD_NUMBER}
      username: admin
      password:
        from_secret: harbor_password
      dockerfile: Dockerfile
      insecure: true

  - name: deploy-to-oracle
    image: appleboy/drone-ssh
    settings:
      host: 10.0.0.1
      username: ubuntu
      key:
        from_secret: oracle_ssh_key
      port: 22
      script:
        - echo "Logging into Harbor..."
        - docker login -u admin -p Harbor12345 10.0.0.2
        - echo "Pulling Portfolio Image..."
        - docker pull 10.0.0.2/library/portfolio:latest
        - echo "Cleaning up old container..."
        - docker rm -f portfolio || true
        - echo "Starting new Portfolio container..."
        - docker run -d --name portfolio -p 80:5000 --restart unless-stopped 10.0.0.2/library/portfolio:latest        - echo "Verifying deployment..."
        - sleep 5
        - docker ps | grep portfolio