apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
  namespace: portfolio
spec:
  replicas: 3
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      imagePullSecrets:
        - name: harbor-secret
      containers:
        - name: portfolio
          image: 10.0.0.2/library/portfolio:latest
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: production
